# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 16:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('load_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleindexpage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(default=datetime.datetime(2016, 7, 17, 16, 55, 28, 983134, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='date',
            field=models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u0441\u0442\u0430\u0442\u044c\u0438'),
        ),
    ]
